apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: martin-test
  namespace: default
spec:
  serviceAccountName: automation
  prune: true
  interval: 1m
  path: "./management-clusters/golem"
  sourceRef:
    kind: GitRepository
    name: martin-test
  timeout: 2m
