---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: argo-cd
  namespace: org-martin
spec:
  catalog: mproffitt-argo-test-catalog
  catalogNamespace: default
  name: argo-cd
  namespace: org-martin
  version: 5.5.6
  kubeConfig:
    inCluster: true
  userConfig:
    configMap:
      name: argo-cd-user-values
      namespace: org-martin
